// Extracts ABIs from `forge build` output into typed TS consts.
// Run from web/:  npm run abis
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const out = resolve(here, "../../out");
const dest = resolve(here, "../src/abis");

const contracts = ["Estate", "EstateVault", "EstateFactory"];

for (const name of contracts) {
  const artifact = resolve(out, `${name}.sol/${name}.json`);
  if (!existsSync(artifact)) {
    console.error(`Missing ${artifact} - run \`forge build\` in the repo root first.`);
    process.exit(1);
  }
  const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
  writeFileSync(
    resolve(dest, `${name}.ts`),
    `// GENERATED by scripts/generate-abis.mjs - do not edit.\n` +
      `// Regenerate with: forge build && npm run abis\n` +
      `export const ${name}Abi = ${JSON.stringify(abi, null, 2)} as const;\n`
  );
  console.log(`wrote src/abis/${name}.ts (${abi.length} entries)`);
}
