// GENERATED by scripts/generate-abis.mjs - do not edit.
// Regenerate with: forge build && npm run abis
export const EstateFactoryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_limits",
        "type": "tuple",
        "internalType": "struct EstateLimits",
        "components": [
          {
            "name": "minHeartbeat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxHeartbeat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minGrace",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxGrace",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minApprovalWindow",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxApprovalWindow",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "allEstates",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "createEstate",
    "inputs": [
      {
        "name": "settings",
        "type": "tuple",
        "internalType": "struct EstateSettings",
        "components": [
          {
            "name": "heartbeatInterval",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "gracePeriod",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "mode",
            "type": "uint8",
            "internalType": "enum DistributionMode"
          }
        ]
      },
      {
        "name": "approvalPolicy",
        "type": "tuple",
        "internalType": "struct ApprovalPolicy",
        "components": [
          {
            "name": "rule",
            "type": "uint8",
            "internalType": "enum ApprovalRule"
          },
          {
            "name": "threshold",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "approvalWindow",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "estate",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "vault",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "estateCountOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "estatesOf",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "limits",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct EstateLimits",
        "components": [
          {
            "name": "minHeartbeat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxHeartbeat",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minGrace",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxGrace",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "minApprovalWindow",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "maxApprovalWindow",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxApprovalWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxGrace",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "maxHeartbeat",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minApprovalWindow",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minGrace",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "minHeartbeat",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "totalEstates",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "EstateCreated",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "estate",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "vault",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidLimits",
    "inputs": []
  }
] as const;
